/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giao_dien;

import entity.NhaPhanPhoi;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frm_NhaPhanPhoi extends javax.swing.JPanel {
    String find_name = "";
    /**
     * Creates new form frm_NhaPhanPhoi
     */
    public frm_NhaPhanPhoi() throws SQLException, ClassNotFoundException {
        initComponents();
        LoadData_NhaPhanPhoi();
    }

    private void LoadData_NhaPhanPhoi() throws SQLException, ClassNotFoundException{
        List<NhaPhanPhoi> lst_NhaPhanPhoi = dao.dao_NhaPhanPhoi.getAllNPP();
        DefaultTableModel tblModel = new DefaultTableModel();
            tblModel.addColumn("Mã Nhà Phân Phối");
            tblModel.addColumn("Tên Nhà Phân Phối");
            tblModel.addColumn("Địa Chỉ");
            tblModel.addColumn("Số Điện thoại");
            tblModel.addColumn("Email");
        for (NhaPhanPhoi npp : lst_NhaPhanPhoi) {
            Vector<String> row = new Vector<String>();
            row.addElement(String.valueOf(npp.getManhaphanphoi()));
            row.addElement(npp.getTennhaphanphoi());
            row.addElement(npp.getDiachi());
            row.addElement(npp.getSdt());
            row.addElement(npp.getEmail());
            tblModel.addRow(row);
        }
        tb_nhaphanphoi.setModel(tblModel);
    }
    private void loadData_control() throws ClassNotFoundException, SQLException, ParseException{
        if (tb_nhaphanphoi.getSelectedRow() != -1) {
            //-- Xác định hàng đã click
            int i = tb_nhaphanphoi.getSelectedRow();
            
            //-- Lấy được danh sách sinh viên
            List<NhaPhanPhoi> lst_npp = dao.dao_NhaPhanPhoi.getAllNPP();
            //-- Xác định là sinh viên nào đang được click
            
            NhaPhanPhoi npp = lst_npp.get(i);
            //--- Set giá trị cho các control
            txt_manhaphanphoi.setText(String.valueOf(npp.getManhaphanphoi()));
            txt_tennhaphanphoi.setText(npp.getTennhaphanphoi());
            txt_diachi.setText(npp.getDiachi());
            txt_sdt.setText(npp.getSdt());
            txt_email.setText(npp.getEmail());
        }
    }
    private void clear(){
        txt_manhaphanphoi.setText("");
        txt_tennhaphanphoi.setText("");
        txt_diachi.setText("");
        txt_sdt.setText("");
        txt_email.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_nhaphanphoi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_manhaphanphoi = new javax.swing.JTextField();
        txt_tennhaphanphoi = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_tim = new javax.swing.JTextField();
        btn_tim = new javax.swing.JButton();

        setBackground(new java.awt.Color(53, 47, 87));

        tb_nhaphanphoi.setBackground(new java.awt.Color(243, 209, 156));
        tb_nhaphanphoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhà Phân Phối", "Tên Nhà Phân Phối", "Địa Chỉ", "Số Điện Thoại", "Email"
            }
        ));
        tb_nhaphanphoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_nhaphanphoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_nhaphanphoi);

        jLabel1.setForeground(new java.awt.Color(221, 245, 165));
        jLabel1.setText("Nhà Phân Phối");

        jLabel2.setForeground(new java.awt.Color(221, 245, 165));
        jLabel2.setText("Mã Nhà Phân Phối");

        jLabel3.setForeground(new java.awt.Color(221, 245, 165));
        jLabel3.setText("Tên Nhà Phân Phối");

        jLabel4.setForeground(new java.awt.Color(221, 245, 165));
        jLabel4.setText("Địa Chỉ");

        jLabel5.setForeground(new java.awt.Color(221, 245, 165));
        jLabel5.setText("Số Điện Thoại");

        jLabel6.setForeground(new java.awt.Color(221, 245, 165));
        jLabel6.setText("Email");

        btn_them.setBackground(new java.awt.Color(184, 72, 99));
        btn_them.setForeground(new java.awt.Color(221, 245, 165));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Add_728898.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(184, 72, 99));
        btn_sua.setForeground(new java.awt.Color(221, 245, 165));
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/replace.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaMouseClicked(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(184, 72, 99));
        btn_xoa.setForeground(new java.awt.Color(221, 245, 165));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaMouseClicked(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(184, 72, 99));
        btn_reset.setForeground(new java.awt.Color(221, 245, 165));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rs.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(221, 245, 165));
        jLabel7.setText("Tìm kiếm");

        txt_tim.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_timCaretUpdate(evt);
            }
        });

        btn_tim.setForeground(new java.awt.Color(221, 245, 165));
        btn_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        btn_tim.setText("Tim");
        btn_tim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tennhaphanphoi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_manhaphanphoi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_them)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_sua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_reset))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_tim))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_manhaphanphoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_tennhaphanphoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_them)
                            .addComponent(btn_sua)
                            .addComponent(btn_xoa)
                            .addComponent(btn_reset))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tim)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void find() throws ClassNotFoundException, SQLException{
    List<NhaPhanPhoi> lstNhaPhanPhoi = dao.dao_NhaPhanPhoi.searchNPP(find_name);
        DefaultTableModel tblModel = new DefaultTableModel();
            tblModel.addColumn("Mã nhà phân phối");
            tblModel.addColumn("Tên nhà phân phối");
            tblModel.addColumn("Địa chỉ");
            tblModel.addColumn("Số điện thoại");
            tblModel.addColumn("Email");
        for (NhaPhanPhoi npp : lstNhaPhanPhoi) {
            Vector<String> row = new Vector<String>();
            row.addElement(String.valueOf(npp.getManhaphanphoi()));
            row.addElement(npp.getTennhaphanphoi());
            row.addElement(npp.getDiachi());
            row.addElement(npp.getSdt());
            row.addElement(npp.getEmail());
            tblModel.addRow(row);
        }
        tb_nhaphanphoi.setModel(tblModel);
    }
    
    private void tb_nhaphanphoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_nhaphanphoiMouseClicked
        try {
            loadData_control();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_nhaphanphoiMouseClicked

    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        NhaPhanPhoi npp = new NhaPhanPhoi();
        npp.setManhaphanphoi(Integer.valueOf(txt_manhaphanphoi.getText()));
        npp.setTennhaphanphoi(txt_tennhaphanphoi.getText());
        npp.setDiachi(txt_diachi.getText());
        npp.setSdt(txt_sdt.getText());
        npp.setEmail(txt_email.getText());
        
        try {
            dao.dao_NhaPhanPhoi.insertNPP(npp);
            LoadData_NhaPhanPhoi();
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Mã bị trùng");
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_themMouseClicked

    private void btn_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaMouseClicked
        NhaPhanPhoi npp = new NhaPhanPhoi();
        npp.setManhaphanphoi(Integer.valueOf(txt_manhaphanphoi.getText()));
        npp.setTennhaphanphoi(txt_tennhaphanphoi.getText());
        npp.setDiachi(txt_diachi.getText());
        npp.setSdt(txt_sdt.getText());
        npp.setEmail(txt_email.getText());
        
    
        try {
            dao.dao_NhaPhanPhoi.updateNPP(npp);
            LoadData_NhaPhanPhoi();
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_suaMouseClicked

    private void btn_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaMouseClicked
        try {
            dao.dao_NhaPhanPhoi.deleteNPP(txt_manhaphanphoi.getText());
            LoadData_NhaPhanPhoi();
            clear();
            JOptionPane.showMessageDialog(this, "Xóa thành công!"); 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_xoaMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        clear();
    }//GEN-LAST:event_btn_resetMouseClicked

    private void btn_timMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timMouseClicked
        find_name = txt_tim.getText();
        try {
            find();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_timMouseClicked

    private void txt_timCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_timCaretUpdate
        find_name = txt_tim.getText();
        try {
            // Bat evrnt day trc
            find();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhaPhanPhoi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_timCaretUpdate
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_nhaphanphoi;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_manhaphanphoi;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tennhaphanphoi;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables
}
