/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giao_dien;
import entity.NhanVien;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class frm_NhanVien extends javax.swing.JPanel {
    String find_name = "";
    /**
     * Creates new form NhanVien
     */
    public frm_NhanVien() throws SQLException, ClassNotFoundException {
        initComponents();
        LoadData_NhanVien();
    }
    private void LoadData_NhanVien() throws SQLException, ClassNotFoundException{
        List<NhanVien> lstNhanVien = dao.dao_NhanVien.getAll();
        DefaultTableModel tblModel = new DefaultTableModel();
            tblModel.addColumn("Mã nhân viên");
            tblModel.addColumn("Tên nhân viên");
            tblModel.addColumn("Ngày sinh");
            tblModel.addColumn("Giới tính");
            tblModel.addColumn("Ngày vào làm");
            tblModel.addColumn("Địa chỉ");
            tblModel.addColumn("Điện thoại");
        for (NhanVien nv : lstNhanVien) {
            Vector<String> row = new Vector<String>();
            row.addElement(String.valueOf(nv.getMaNV()));
            row.addElement(nv.getTenNV());
            row.addElement(String.valueOf(nv.getNgaySinh()));
            row.addElement(String.valueOf(nv.getGioiTinh()));
            row.addElement(String.valueOf(nv.getNgayVaoLam()));
            row.addElement(nv.getDiaChi());
            row.addElement(nv.getSdt());
            tblModel.addRow(row);
        }
        tbNhanVien.setModel(tblModel);
    }
    
    private void loadData_control() throws ClassNotFoundException, SQLException, ParseException{
        if (tbNhanVien.getSelectedRow() != -1) {
            //-- Xác định hàng đã click
            int i = tbNhanVien.getSelectedRow();
            
            //-- Lấy được danh sách sinh viên
            List<NhanVien> lstnv = dao.dao_NhanVien.getAll();
            //-- Xác định là sinh viên nào đang được click
            
            NhanVien nv = lstnv.get(i);
            //--- Set giá trị cho các control
            txt_manhanvien.setText(String.valueOf(nv.getMaNV()));
            txt_tennhanvien.setText(nv.getTenNV());
            int check = nv.getGioiTinh();
            if (check == 1) {
                rd_nam.setSelected(true);
            }
            else if (check == 0) {
                rd_nu.setSelected(true);
            }
            txt_diachi.setText(nv.getDiaChi());
            txt_sdt.setText(nv.getSdt());
            //- Xác định lớp học của sv1                          
            //- Set giá trị của components JXdatepicker
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            date_ngaysinh.setDate(dateFormat.parse(nv.getNgaySinh()));
            date_ngayvaolam.setDate(dateFormat.parse(nv.getNgayVaoLam()));
        }
    }
    private void find() throws ClassNotFoundException, SQLException{
    List<NhanVien> lstNhanVien = dao.dao_NhanVien.searchNV(find_name);
        DefaultTableModel tblModel = new DefaultTableModel();
            tblModel.addColumn("Mã nhân viên");
            tblModel.addColumn("Tên nhân viên");
            tblModel.addColumn("Ngày sinh");
            tblModel.addColumn("Giới tính");
            tblModel.addColumn("Ngày vào làm");
            tblModel.addColumn("Địa chỉ");
            tblModel.addColumn("Điện thoại");
        for (NhanVien nv : lstNhanVien) {
            Vector<String> row = new Vector<String>();
            row.addElement(String.valueOf(nv.getMaNV()));
            row.addElement(nv.getTenNV());
            row.addElement(String.valueOf(nv.getNgaySinh()));
            row.addElement(String.valueOf(nv.getGioiTinh()));
            row.addElement(String.valueOf(nv.getNgayVaoLam()));
            row.addElement(nv.getDiaChi());
            row.addElement(nv.getSdt());
            tblModel.addRow(row);
        }
        tbNhanVien.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_manhanvien = new javax.swing.JTextField();
        txt_tennhanvien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date_ngaysinh = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        rd_nam = new javax.swing.JRadioButton();
        rd_nu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        date_ngayvaolam = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNhanVien = new org.jdesktop.swingx.JXTable();
        btn_search = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(53, 47, 87));
        setForeground(new java.awt.Color(221, 245, 165));

        jLabel1.setForeground(new java.awt.Color(221, 245, 165));
        jLabel1.setText("Mã nhân viên:");

        jLabel2.setForeground(new java.awt.Color(221, 245, 165));
        jLabel2.setText("Tên nhân viên:");

        jLabel3.setForeground(new java.awt.Color(221, 245, 165));
        jLabel3.setText("Ngày sinh:");

        jLabel4.setForeground(new java.awt.Color(221, 245, 165));
        jLabel4.setText("Giới Tính:");

        buttonGroup1.add(rd_nam);
        rd_nam.setForeground(new java.awt.Color(221, 245, 165));
        rd_nam.setText("Nam");

        buttonGroup1.add(rd_nu);
        rd_nu.setForeground(new java.awt.Color(221, 245, 165));
        rd_nu.setText("Nữ");

        jLabel5.setForeground(new java.awt.Color(221, 245, 165));
        jLabel5.setText("Ngày vào làm:");

        jLabel6.setForeground(new java.awt.Color(221, 245, 165));
        jLabel6.setText("SĐT:");

        txt_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diachiActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(221, 245, 165));
        jLabel7.setText("Địa chỉ:");

        btn_them.setBackground(new java.awt.Color(184, 72, 99));
        btn_them.setForeground(new java.awt.Color(221, 245, 165));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Add_728898.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(184, 72, 99));
        btn_sua.setForeground(new java.awt.Color(221, 245, 165));
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/replace.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaMouseClicked(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(184, 72, 99));
        btn_xoa.setForeground(new java.awt.Color(221, 245, 165));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaMouseClicked(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(184, 72, 99));
        btn_reset.setForeground(new java.awt.Color(221, 245, 165));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rs.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });

        tbNhanVien.setBackground(new java.awt.Color(243, 209, 156));
        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Tên nhân viên", "Ngày sinh", "Giới tính", "Ngày vào làm", "Địa chỉ", "Điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbNhanVien);

        btn_search.setBackground(new java.awt.Color(184, 72, 99));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find.png"))); // NOI18N
        btn_search.setText("Tìm");
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        txt_search.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_searchCaretUpdate(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(221, 245, 165));
        jLabel8.setText("Tìm kiếm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_manhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_sdt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rd_nam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rd_nu))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(date_ngayvaolam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_manhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_nam)
                    .addComponent(rd_nu)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_ngayvaolam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diachiActionPerformed

    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        Date dtn_ns = date_ngaysinh.getDate();
        Date dtn_nvl = date_ngayvaolam.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        NhanVien nv = new NhanVien();
        nv.setMaNV(Integer.valueOf(txt_manhanvien.getText()));
        nv.setTenNV(txt_tennhanvien.getText());
        nv.setNgaySinh(dateFormat.format(dtn_ns));
        nv.setNgayVaoLam(dateFormat.format(dtn_nvl));
        nv.setDiaChi(txt_diachi.getText());
        nv.setSdt(txt_sdt.getText());
        if (rd_nam.isSelected() == true) {
            nv.setGioiTinh(1);
        }
        else if (rd_nu.isSelected() == true) {
            nv.setGioiTinh(0);
        }
        
        try {
            dao.dao_NhanVien.insertNV(nv);
            JOptionPane.showMessageDialog(this,"Thêm thành công");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Mã bị trùng");
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            LoadData_NhanVien();
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_themMouseClicked

    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        try {
            loadData_control();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbNhanVienMouseClicked

    private void btn_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaMouseClicked
        Date dtn_ns = date_ngaysinh.getDate();
        Date dtn_nvl = date_ngayvaolam.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        NhanVien nv = new NhanVien();
        nv.setMaNV(Integer.valueOf(txt_manhanvien.getText()));
        nv.setTenNV(txt_tennhanvien.getText());
        nv.setDiaChi(txt_diachi.getText());
        nv.setNgaySinh(dateFormat.format(dtn_ns));
        nv.setNgayVaoLam(dateFormat.format(dtn_nvl));
        nv.setSdt(txt_sdt.getText());
        if (rd_nam.isSelected() == true) {
            nv.setGioiTinh(1);
        }
        else if (rd_nu.isSelected() == true) {
            nv.setGioiTinh(0);
        }
        try {
            dao.dao_NhanVien.updateNV(nv);
            LoadData_NhanVien();
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_suaMouseClicked

    private void btn_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaMouseClicked
        try {
            dao.dao_NhanVien.deleteNV(txt_manhanvien.getText());
            JOptionPane.showMessageDialog(this,"Xóa thành công");
            LoadData_NhanVien();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_xoaMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        txt_manhanvien.setText("");
        txt_diachi.setText("");
        txt_sdt.setText("");
        txt_tennhanvien.setText("");
    }//GEN-LAST:event_btn_resetMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        find_name = txt_search.getText();
        try {
            find();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_searchMouseClicked

    private void txt_searchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_searchCaretUpdate
        find_name = txt_search.getText();
        try {
            find();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_searchCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdesktop.swingx.JXDatePicker date_ngaysinh;
    private org.jdesktop.swingx.JXDatePicker date_ngayvaolam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nu;
    private org.jdesktop.swingx.JXTable tbNhanVien;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_manhanvien;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_tennhanvien;
    // End of variables declaration//GEN-END:variables
}
